version: '3.9'
services:
  lambda:
    env_file: .env
    image: ${REPO:-amancevice/slackbot-slash-command}
    network_mode: bridge
    ports:
      - 8080
    volumes:
      - ~/.aws:/root/.aws
      - root:/root
      # - ./:/var/task
volumes:
  root:
